#!/usr/bin/env -S node --experimental-strip-types
/**
 * sql-reactive-orm codegen
 *
 *   sql-reactive-orm-codegen --config <orm.config.ts> --out <dir>
 *
 * Reads the user's ORM config (a `.ts` / `.js` module with a default
 * export of `{ entities: [...] }`), and emits two files under `<dir>`:
 *
 *   schema.sql  — `CREATE TABLE IF NOT EXISTS …` DDL, one statement per
 *                 registered entity. Feed this to kysely-codegen (or
 *                 any other schema-driven tool) if you prefer its
 *                 output over the bundled type emitter.
 *
 *   db.ts       — a kysely-compatible `DB` interface plus one row
 *                 interface per table, derived directly from the
 *                 entity schemas. Import it to type `Kysely<DB>`:
 *
 *                   import type { DB } from './generated/db'
 *                   const orm = new Orm<DB>(driver)
 *                   use(orm.sqlQuery((db) => db.selectFrom('…')…))
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { generateDDL } from "../schema.js";
import type { EntityClass, FieldDef } from "../schema.js";

interface OrmConfig {
  entities: readonly EntityClass[];
}

function parseArgs(argv: readonly string[]): {
  config: string;
  out: string;
} {
  let config: string | undefined;
  let out: string | undefined;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]!;
    if (a === "--config" || a === "-c") config = argv[++i];
    else if (a.startsWith("--config=")) config = a.slice("--config=".length);
    else if (a === "--out" || a === "-o") out = argv[++i];
    else if (a.startsWith("--out=")) out = a.slice("--out=".length);
    else if (!a.startsWith("-")) {
      if (!config) config = a;
      else if (!out) out = a;
    }
  }
  if (!config || !out) {
    console.error(
      "Usage: sql-reactive-orm-codegen --config <orm.config.ts> --out <dir>",
    );
    process.exit(1);
  }
  return {
    config: isAbsolute(config) ? config : resolve(process.cwd(), config),
    out: isAbsolute(out) ? out : resolve(process.cwd(), out),
  };
}

async function loadConfig(path: string): Promise<OrmConfig> {
  const mod = (await import(pathToFileURL(path).href)) as {
    default?: OrmConfig;
    config?: OrmConfig;
  };
  const config = mod.default ?? mod.config;
  if (!config || !Array.isArray(config.entities)) {
    throw new Error(
      `${path} must export \`{ entities: [...] }\` as its default export`,
    );
  }
  return config;
}

function emitSchemaSql(entities: readonly EntityClass[]): string {
  const stmts = entities.map((e) => generateDDL(e.schema) + ";");
  return (
    [
      "-- Generated by sql-reactive-orm-codegen.",
      "-- Re-run `pnpm codegen` after changing any entity schema.",
      "",
      ...stmts,
      "",
    ].join("\n") + "\n"
  );
}

function tsTypeFor(field: FieldDef): string {
  let base: string;
  if (field.json) base = "unknown";
  else if (field.boolean) base = "boolean";
  else if (field.type === "INTEGER" || field.type === "REAL") base = "number";
  else if (field.type === "TEXT") base = "string";
  else if (field.type === "BLOB") base = "Uint8Array";
  else base = "unknown";
  return field.nullable ? `${base} | null` : base;
}

function interfaceName(entityName: string): string {
  // `Transaction` → `TransactionRow`
  return `${entityName}Row`;
}

function emitDbTs(entities: readonly EntityClass[]): string {
  const rows = entities.map((e) => ({
    tableName: e.schema.table,
    rowType: interfaceName(e.schema.name),
    fields: Object.entries(e.schema.fields).map(([name, def]) => ({
      name,
      ts: tsTypeFor(def),
    })),
  }));
  const lines: string[] = [
    "// Generated by sql-reactive-orm-codegen. Do not edit by hand.",
    "// Kysely-compatible row shapes, one per registered entity.",
    "",
  ];
  for (const r of rows) {
    lines.push(`export interface ${r.rowType} {`);
    for (const f of r.fields) {
      // Quote the key when it's not a valid JS identifier so kysely's
      // inference still works for exotic column names.
      const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(f.name)
        ? f.name
        : JSON.stringify(f.name);
      lines.push(`  ${key}: ${f.ts};`);
    }
    lines.push(`}`);
    lines.push("");
  }
  lines.push("/** Table name → row shape map consumed by `Kysely<DB>`. */");
  lines.push("export interface DB {");
  for (const r of rows) {
    lines.push(`  ${JSON.stringify(r.tableName)}: ${r.rowType};`);
  }
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

async function main(): Promise<void> {
  const { config: configPath, out: outDir } = parseArgs(process.argv.slice(2));
  const config = await loadConfig(configPath);
  mkdirSync(outDir, { recursive: true });
  const schemaPath = resolve(outDir, "schema.sql");
  const dbPath = resolve(outDir, "db.ts");
  writeFileSync(schemaPath, emitSchemaSql(config.entities));
  writeFileSync(dbPath, emitDbTs(config.entities));
  const rel = (p: string): string => {
    try {
      return "./" + (p.startsWith(process.cwd())
        ? p.slice(process.cwd().length + 1)
        : p);
    } catch {
      return p;
    }
  };
  console.log(
    `${config.entities.length} entit${config.entities.length === 1 ? "y" : "ies"} · wrote`,
  );
  console.log(`  ${rel(schemaPath)}`);
  console.log(`  ${rel(dbPath)}`);
  // `dirname` imported purely so the function is used if future
  // refactors need it; keeps the import list honest.
  void dirname;
}

main().catch((e: unknown) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
